### ISSUE TITLE
Uncaught TokenResponseException, cURL timed out after 0 milliseconds with 0 out of 0 bytes received

### ISSUE THREAD

**Issue by samwilson** [mistic100/Flickr2Piwigo#32]
Seems to be perhaps a rate-limiting, so doesn't matter (any missed photo will be caught on the next run) but we should make it work better than this.

```
Fatal error: Uncaught OAuth\Common\Http\Exception\TokenResponseException:
cURL Error # 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received in
plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php:135

Stack trace:
#0 plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(98):
   OAuth\Common\Http\Client\CurlClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), 'photo_ids=36061...', Array, 'POST')
#1 plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(124):
   OAuth\OAuth1\Service\Flickr->request('flickr.photoset...', 'POST', Array, Array) 
#2 plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/PhpFlickr.php(347):
   OAuth\OAuth1\Service\Flickr->requestJson('flickr.photoset...', 'POST', Array) 
#3 plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/Photos
   in plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php on line 135
 ```

**Comment by plegall** [comment]
Same error was reported from a Piwigo.com user. In the meantime, I have made some search among Piwigo.com accounts and others have been able to use the plugin without this blocking error.
