### ISSUE TITLE
Fatal error when opening import tab

### ISSUE THREAD

**Issue by ashinalsace** [mistic100/Flickr2Piwigo#43]
Hi, 

I have tried to install the plugin.

Adding the keys works, but when I open the import tab I get the following message

Fatal error: Uncaught Error: Call to undefined function OAuth\Common\Http\Client\curl_init() in 
plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php:86 Stack trace: #0 plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(98): OAuth\Common\Http\Client\CurlClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), Array, Array, 'POST') #1 plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php(124): OAuth\OAuth1\Service\Flickr->request('flickr.test.log...', 'POST', Array, Array) #2 plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/PhpFlickr.php(347): OAuth\OAuth1\Service\Flickr->requestJson('flickr.test.log...', 'POST', Array) #3 plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/TestApi.php(31): Samwilson\PhpFlickr\PhpFlickr->request('flickr.test.log in plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php on line 86

I did not complete this setup "7) on the Flickr page, click on the “Edit auth flow for this app” link and copy your Callback URL, provided on Flickr2Piwigo configuration page." as I am not sure where the URL is provided. Could this be the issue?

Thanks for any help

Ash

**Comment by samwilson** [comment]
It sounds like you might not have [Curl](https://secure.php.net/manual/en/book.curl.php) installed. Can you check that?

We should add a check to the plugin, so it shows a nicer error message earlier on in the process.

**Comment by ashinalsace** [comment]
Hi,
Thanks for reply but curl seems to be installed

```
$ curl --version
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2q zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

```

My installed has Debian 9 with Ngnix 

Happy New Year !

**Comment by samwilson** [comment]
You may also need to install the `php-curl` package, and do `sudo phpenmod curl`.

**Comment by ashinalsace** [comment]
That fixed it  :)
Thanks.

**Comment by samwilson** [comment]
Hurrah, glad to hear it. :)

If you find any other problems, do open issues here for them (if they're not already tracked; there are some glaring known problems :( ).

**Comment by ToSvo** [comment]
Hi,
I have similar problem with plugin:

Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /www/doc/www.kosikareni.cz/www/photostomas/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php on line 107

Warning: Cannot modify header information - headers already sent by (output started at /www/doc/www.kosikareni.cz/www/photostomas/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php:107) in /www/doc/www.kosikareni.cz/www/photostomas/include/page_header.php on line 101

my PHP 5.5.38
cURL support | enabled
-- | --
cURL Information | 7.52.1
Age | 3
Features
AsynchDNS | Yes
CharConv | No
Debug | No
GSS-Negotiate | No
IDN | Yes
IPv6 | Yes
krb4 | No
Largefile | Yes
libz | Yes
NTLM | Yes
NTLMWB | Yes
SPNEGO | Yes
SSL | Yes
SSPI | No
TLS-SRP | Yes
Protocols | dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host | x86_64-pc-linux-gnu
SSL Version | OpenSSL/1.0.2q
ZLib Version | 1.2.8
libSSH Version | libssh2/1.7.0

**Comment by samwilson** [comment]
That's a different issue. It's due to you having [open_basedir](https://secure.php.net/manual/en/ini.core.php#ini.open-basedir) set. Are you able to disable it?

**Comment by ToSvo** [comment]
I'm afraid not.
